export default [
  {
    text: "Bab 1: Pendahuluan",
    collapsed: true, // Bisa di-collapse biar rapi
    items: [
      { text: "Latar Belakang", link: "/research-codesearch/introduction/background" },
      { text: "Tujuan Riset", link: "/research-codesearch/introduction/objectives" },
    ],
  },
  {
    text: "Bab 2: Kajian Pustaka",
    collapsed: true, // Bisa di-collapse biar rapi
    items: [
      // { text: 'Ringkasan', link: '/literature-review/' },
      // { text: 'Traditional IR (BM25)', link: '/literature-review/ir-based' },
      // { text: 'Deep Learning Models', link: '/literature-review/deep-learning' },
      // { text: 'LLM & Generative', link: '/literature-review/llm-based' },
      // { text: 'TEMPLATE', link: '/literature-review/template' },
      { link: "/research-codesearch/literature-review/1001", text: "1001 - Architectural Recognition (Harris et al., 1996)" },
      { link: "/research-codesearch/literature-review/1002", text: "1002 - SCRUPLE Discussion (Devanbu, 1995)" },
      { link: "/research-codesearch/literature-review/1003", text: "1003 - Architectural Recognition (Harris et al., 1996)" },
      { link: "/research-codesearch/literature-review/1004", text: "1004 - APS Synthesis (Kazimierczak, 1996)" },
      { link: "/research-codesearch/literature-review/1005", text: "1005 - ARDEX (Arima, 1996)" },
      { link: "/research-codesearch/literature-review/1006", text: "1006 - SCA Algebra (Paul & Prakash, 1996)" },
      { link: "/research-codesearch/literature-review/1007", text: "1007 - Knowledge Reduction (Mira et al., 1998)" },
      { link: "/research-codesearch/literature-review/1008", text: "1008 - Error-Correcting Source (Ajiro et al., 1998)" },
      { link: "/research-codesearch/literature-review/1009", text: "1009 - Mobile Thesaurus (Honiden, 2000)" },
      { link: "/research-codesearch/literature-review/1010", text: "1010 - Error-Correcting Source (Ajiro et al., 1998)" },
      { link: "/research-codesearch/literature-review/1011", text: "1011 - Data Novice Tools (Card et al., 2003)" },
      { link: "/research-codesearch/literature-review/1012", text: "1012 - combinFormation (Kerne et al., 2003)" },
      { link: "/research-codesearch/literature-review/1013", text: "1013 - Component Search (Washizaki & Fukazawa, 2004)" },
      { link: "/research-codesearch/literature-review/1014", text: "-1014 - TS-DSC Tool (Balasingham & Zhang, 2004)" },
      { link: "/research-codesearch/literature-review/1015", text: "1015 - Incremental Change (Rajlich & Gosavi, 2004)" },
      { link: "/research-codesearch/literature-review/1016", text: "1016 - JavaBeans Search (Washizaki & Fukazawa, 2004)" },
      { link: "/research-codesearch/literature-review/1017", text: "1017 - Component Reuse System (Washizaki & Fukazawa, 2005)" },
      { link: "/research-codesearch/literature-review/1018", text: "1018 - CodeQuest (Hajiyev et al., 2006)" },
      { link: "/research-codesearch/literature-review/1019", text: "1019 - MAPO (Xie & Pei, 2006)" },
      { link: "/research-codesearch/literature-review/1020", text: "1020 - Sourcerer (Bajracharya et al., 2006)" },
      { link: "/research-codesearch/literature-review/1021", text: "1021 - RiSE Search (Garcia et al., 2006)" },
      { link: "/research-codesearch/literature-review/1022", text: "1022 - SCR-Integration (Yusof & Rana, 2007)" },
      { link: "/research-codesearch/literature-review/1023", text: "1023 - OrcA (Bhagwan et al., 2007/2018)" },
      { link: "/research-codesearch/literature-review/1024", text: "1024 - Clone Search (Dean et al., 2007)" },
      { link: "/research-codesearch/literature-review/1025", text: "1025 - Reference Vectors (Ohno & Murao, 2007)" },
      { link: "/research-codesearch/literature-review/1026", text: "1026 - PSSA (Miki et al., 2007)" },
      { link: "/research-codesearch/literature-review/1027", text: "1027 - CodeGenie (Lemos et al., 2007)" },
      { link: "/research-codesearch/literature-review/1028", text: "1028 - SemmleCode (Verbaere et al., 2007)" },
      { link: "/research-codesearch/literature-review/1029", text: "1029 - CSE Framework (Thummalapenta, 2007)" },
      { link: "/research-codesearch/literature-review/1030", text: "1030 - PARSEWeb (Thummalapenta & Xie, 2007)" },
      { link: "/research-codesearch/literature-review/1031", text: "1031 - CodeGenie (Lemos et al., 2007)" },
      { link: "/research-codesearch/literature-review/1032", text: "1032 - CSF-Retrieval (Yusof & Rana, 2008)" },
      { link: "/research-codesearch/literature-review/1033", text: "1033 - Semantic Layer Search (Durão et al., 2008)" },
      { link: "/research-codesearch/literature-review/1034", text: "1034 - Combinator GP (Briggs & O’Neill, 2008)" },
      { link: "/research-codesearch/literature-review/1035", text: "1035 - SpotWeb (Thummalapenta & Xie, 2008)" },
      { link: "/research-codesearch/literature-review/1036", text: "1036 - Code Conjurer (Hummel et al., 2008)" },
      { link: "/research-codesearch/literature-review/1037", text: "1037 - Source Code Search Roadmap (Happel et al., 2008)" },
      { link: "/research-codesearch/literature-review/1038", text: "1038 - QueryTech (Verbaere et al., 2008)" },
      { link: "/research-codesearch/literature-review/1039", text: "1039 - SpotWeb (Thummalapenta & Xie, 2008)" },
      { link: "/research-codesearch/literature-review/1040", text: "1040 - CollabDev (Sarkar et al., 2008)" },
      { link: "/research-codesearch/literature-review/1041", text: "1041 - LDA Bug Localization (Lukins et al., 2008)" },
      { link: "/research-codesearch/literature-review/1042", text: "1042 - Samurai (Enslen et al., 2009)" },
      { link: "/research-codesearch/literature-review/1043", text: "1043 - Koders Log Analysis (Bajracharya & Lopes, 2009)" },
      { link: "/research-codesearch/literature-review/1044", text: "1044 - Sourcerer (Linstead et al., 2009)" },
      { link: "/research-codesearch/literature-review/1045", text: "1045 - Cognac (Kellens et al., 2009)" },
      { link: "/research-codesearch/literature-review/1046", text: "1046 - SNIFF (Chatterjee et al., 2009)" },
      { link: "/research-codesearch/literature-review/1047", text: "1047 - MAPO (Zhong et al., 2009)" },
      { link: "/research-codesearch/literature-review/1048", text: "1048 - WYSIWIB (Lawall et al., 2009)" },
      { link: "/research-codesearch/literature-review/1049", text: "1049 - CodeGenie (Lemos et al., 2009)" },
      { link: "/research-codesearch/literature-review/1050", text: "1050 - Non-Programmer Search (Gross & Kelleher, 2009)" },
      { link: "/research-codesearch/literature-review/1051", text: "1051 - Pointcut-QBE (Cisternino & Vaucouleur, 2009)" },
      { link: "/research-codesearch/literature-review/1052", text: "1052 - SUITE-LifeCycle (Marri et al., 2009)" },
      { link: "/research-codesearch/literature-review/1053", text: "1053 - Sourcerer (Bajracharya et al., 2009)" },
      { link: "/research-codesearch/literature-review/1054", text: "1054 - ISCS (Gallardo-Valencia & Sim, 2009)" },
      { link: "/research-codesearch/literature-review/1055", text: "1055 - WSR (Starke et al., 2009)" },
      { link: "/research-codesearch/literature-review/1056", text: "1056 - Code Conjurer (Janjic et al., 2009)" },
      { link: "/research-codesearch/literature-review/1057", text: "1057 - Context-NL (Hill et al., 2009)" },
      { link: "/research-codesearch/literature-review/1058", text: "1058 - S6 (Reiss, 2009)" },
      { link: "/research-codesearch/literature-review/1059", text: "1059 - Alattin (Thummalapenta & Xie, 2009)" },
      { link: "/research-codesearch/literature-review/1060", text: "1060 - Comment-Reuse (Álvarez-González et al., 2009)" },
      { link: "/research-codesearch/literature-review/1061", text: "1061 - SCA-Edu (Stanford & Erbach, 2009)" },
      { link: "/research-codesearch/literature-review/1062", text: "1062 - S6-Demo (Reiss, 2009)" },
      { link: "/research-codesearch/literature-review/1063", text: "1063 - Skimming-Study (Starke et al., 2009)" },
      { link: "/research-codesearch/literature-review/1064", text: "1064 - Eggther (Vaucouleur, 2009)" },
      { link: "/research-codesearch/literature-review/1065", text: "1065 - D-CUBED (Wȩgrzynowicz & Stencel, 2009)" },
      { link: "/research-codesearch/literature-review/1066", text: "1066 - MMMF-Code (Weimer et al., 2009)" },
      { link: "/research-codesearch/literature-review/1067", text: "1067 - API-OntoSearch (Alnusair et al., 2010)" },
      { link: "/research-codesearch/literature-review/1068", text: "1068 - BART (Reis Santos et al., 2010)" },
      { link: "/research-codesearch/literature-review/1069", text: "1069 - Intelligent Code Search (Kim et al., 2010)" },
      { link: "/research-codesearch/literature-review/1070", text: "1070 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1071", text: "1071 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1072", text: "1072 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1073", text: "1073 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1074", text: "1074 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1075", text: "1075 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1076", text: "1076 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1077", text: "1077 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1078", text: "1078 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1079", text: "1079 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1080", text: "1080 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1081", text: "1081 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1082", text: "1082 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1083", text: "1083 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1084", text: "1084 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1085", text: "1085 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1086", text: "1086 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1087", text: "1087 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1088", text: "1088 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1089", text: "1089 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1090", text: "1090 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1091", text: "1091 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1092", text: "1092 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1093", text: "1093 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1094", text: "1094 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1095", text: "1095 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1096", text: "1096 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1097", text: "1097 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1098", text: "1098 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1099", text: "1099 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1100", text: "1100 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1101", text: "1101 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1102", text: "1102 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1103", text: "1103 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1104", text: "1104 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1105", text: "1105 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1106", text: "1106 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1107", text: "1107 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1108", text: "1108 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1109", text: "1109 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1110", text: "1110 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1111", text: "1111 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1112", text: "1112 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1113", text: "1113 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1114", text: "1114 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1115", text: "1115 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1116", text: "1116 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1117", text: "1117 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1118", text: "1118 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1119", text: "1119 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1120", text: "1120 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1121", text: "1121 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1122", text: "1122 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1123", text: "1123 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1124", text: "1124 - TEMPLATE" },
      { link: "/research-codesearch/literature-review/1125", text: "1125 - TEMPLATE" },
    ],
  },
  {
    text: "Bab 3: Metodologi",
    collapsed: true, // Bisa di-collapse biar rapi
    items: [
      { text: "Dataset (CodeSearchNet)", link: "/research-codesearch/methodology/dataset" },
      { text: "Preprocessing (AST)", link: "/research-codesearch/methodology/preprocessing" },
      { text: "Arsitektur Model", link: "/research-codesearch/methodology/model-architecture" },
    ],
  },
  {
    text: "Bab 4: Eksperimen",
    collapsed: true, // Bisa di-collapse biar rapi
    items: [
      { text: "Metrik Evaluasi (MRR)", link: "/research-codesearch/experiments/metrics" },
      { text: "Hasil & Diskusi", link: "/research-codesearch/experiments/results" },
    ],
  },
  {
    text: "Bab 5: Penutup",
    collapsed: true, // Bisa di-collapse biar rapi
    items: [{ text: "Kesimpulan", link: "/research-codesearch/conclusion/" }],
  },
];
